### ISSUE TITLE
Produce test vectors for `did:jwk`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/sdk-development#12]
Produce language agnostic test vectors that can be used by each implementation to ensure that the following features work correctly:
* Creation
* Resolution

Related: #17

**Comment by mistermoe** [comment]
related: https://github.com/TBD54566975/web5-kt/pull/136

**Comment by decentralgabe** [comment]
I recommend starting with [these existing test vectors](https://github.com/OR13/did-jwk/blob/main/src/signatures-test-vectors.json).

**Comment by frankhinek** [comment]
@decentralgabe those were used as a base but can't be used as written because they don't entirely follow the `did:jwk` spec as written.

See: https://github.com/OR13/did-jwk/issues/4

**Comment by decentralgabe** [comment]
thanks @frankhinek I recommend that we open issues on the [spec repo itself](https://github.com/quartzjer/did-jwk) or create our own vectors based on Orie's vectors and open a PR back to the main spec.

**Comment by mistermoe** [comment]
resolve vectors done. [lives here](https://github.com/TBD54566975/sdk-development/tree/main/web5-test-vectors/did_jwk)
