### ISSUE TITLE
Decide on supported feature set for Presentation Exchange

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/sdk-development#16]

**Comment by decentralgabe** [comment]
I believe we should support [PEv2](https://identity.foundation/presentation-exchange/spec/v2.0.0/), with the following features:
- [Predicates](https://identity.foundation/presentation-exchange/spec/v2.0.0/#predicate-feature) (e.g. be able to filter that a field is of a certain regex, length, etc.)
- [Relational Constraints](https://identity.foundation/presentation-exchange/spec/v2.0.0/#relational-constraint-feature) (e.g. require a credential to be self-issued, or not)
- [Credential Status](https://identity.foundation/presentation-exchange/spec/v2.0.0/#credential-status-constraint-feature) (e.g. be able to require that a credential is of a certain status)

The features I've excluded: submission requirements, JSON-LD framing, retention. Everything else should be according to the spec.

**Comment by mahoekst** [comment]
relational contraints is also give me a VC from this specific issuer correct?

**Comment by decentralgabe** [comment]
@mahoekst that would be predicates

**Comment by mistermoe** [comment]
cc: @nitro-neal

**Comment by mistermoe** [comment]
cc: @nitro-neal

**Comment by mahoekst** [comment]
I would recommend the minimum to support give me a VC of type X from issuer Y where both are optional.

**Comment by mistermoe** [comment]
before closing this issue, we probably want to document this feature set in the README. @decentralgabe can you tackle that if possible?

**Comment by decentralgabe** [comment]
https://github.com/TBD54566975/sdk-development/pull/96
