### ISSUE TITLE
Create repo for rust sdk

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/sdk-development#18]
`*-rs`. 

@amika-sq, followup question, what's your perspective on whether swift should live in the same repo or in a separate. Instinctively (maybe naively) thinking separate repos

**Comment by amika-sq** [comment]
For starters, I'd like to keep it to one to reduce complexity. This is already massively complex, so I'd say let's make our lives a little bit easier!

Eventually, I think two separate repos will be the path forward, but I don't know enough to make that happen yet.

**Comment by amika-sq** [comment]
https://github.com/TBD54566975/web5-rs
https://github.com/TBD54566975/tbdex-rs

**Comment by amika-sq** [comment]
I can't close this issue. It's complete.

**Comment by mistermoe** [comment]
thanks @amika-sq! PR that includes relevant links: #26
