### ISSUE TITLE
Create Github labels and Milestones in each sdk repo

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/sdk-development#19]
I have scripts ready [here](https://github.com/TBD54566975/sdk-development/tree/main/scripts/github) to make this less grueling

- [x] `tbdex-js`
- [x] `tbdex-kt`
- [x] `web5-js`
- [x] `web5-kt`

**Comment by frankhinek** [comment]
@mistermoe The milestones and labels have been added to the `web5-js` repo.

On that note, do we want the `web5-js` and `web5-kt` repos to contain the following labels or should they only exist in `tbdex-js` and `tbdex-kt`?

- tbdex-message
- tbdex-resource
- tbdex-offering
- tbdex-rfq
- tbdex-quote
- tbdex-order
- tbdex-orderstatus
- tbdex-close

**Comment by phoebe-lew** [comment]
@frankhinek I think the tbdex ones are pretty decoupled from web5, so we can just create the list that you mentioned for `tbdex-x`repos. @mistermoe similarly, some of those web5 related ones probably don't make sense to create in tbdex.

**Comment by mistermoe** [comment]
makes sense to me

**Comment by frankhinek** [comment]
> @frankhinek I think the tbdex ones are pretty decoupled from web5, so we can just create the list that you mentioned for `tbdex-x`repos. @mistermoe similarly, some of those web5 related ones probably don't make sense to create in tbdex.

Sounds good.  Removed the `tbdex-*` labels from `web5-js`

**Comment by mistermoe** [comment]
noice! closing this out
