### ISSUE TITLE
Create Github Issues for CI/CD related work items in each respective sdk repo

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/sdk-development#21]
CI/CD related work items [here](https://github.com/TBD54566975/sdk-development#ci--cd)

let me know if i'm off the mark on any of these @leordev

**Comment by leordev** [comment]
@mistermoe I created all the aggregated tasks for CI/CD below.

Please let me know if you want me to make them granular per SDK repo.

#37 
#38 
#39 
#40 
#41 
#42 
#43 
#44 
#45 
#46 
#47

**Comment by mistermoe** [comment]
i think making them granular per repo makes sense! related: https://github.com/TBD54566975/sdk-development/issues/22#issuecomment-1804796018

**Comment by leordev** [comment]
Done! They are all created! https://github.com/orgs/TBD54566975/projects/29/views/6?sliceBy%5Bvalue%5D=cicd
