### ISSUE TITLE
Create all necessary issues in `web5-js` repo

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/sdk-development#22]
@frankhinek can you take a look at this repo's [README](https://github.com/TBD54566975/sdk-development#readme) and create all necessary issues in `web5-js`?

Related issues: #19 #21

**Comment by frankhinek** [comment]
Completed #19 

Working through the README to add/update issues.  Will update this issue with questions or once its done.

**Comment by frankhinek** [comment]
Added issues for each feature that has not been implemented.

CI/CD issues still to be created.
