### ISSUE TITLE
Produce test vectors for PEX

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/sdk-development#55]
Can use many of these here:
https://github.com/TBD54566975/ssi-sdk/tree/main/credential/exchange/testdata

**Comment by decentralgabe** [comment]
@nitro-neal agree on using those they're taking from the spec itself

**Comment by nitro-neal** [comment]
https://github.com/TBD54566975/sdk-development/blob/main/web5-test-vectors/presentation-exchange/wa-license.json
