### ISSUE TITLE
Decide on a kotlin SDK publishing solution

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/sdk-development#63]
Currently using jitpack, not viable in the long term. 

Context: https://sq-tbd.slack.com/archives/C05SXUR39FE/p1696907744806279, https://github.com/TBD54566975/web5-kt/issues/68

**Comment by bradleydwyer** [comment]
There is an ongoing effort related to supply-chain security run by @ALRubinger and @leordev that has overlap with this. Links to this doc will be shared in our internal discussion channel.

**Comment by mistermoe** [comment]
Landed on maven central
