### ISSUE TITLE
Question about DID Resolution Test Vectors

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/sdk-development#76]
`resolve` function test vectors for `did:jwk` and `did:web` have been committed to the [sdk-development](https://github.com/TBD54566975/sdk-development) repo and others will be added fairly soon.  There are inconsistencies in the existing two vectors that would be good to resolve before we modify the SDKs that are consuming these vectors (and cover more DID methods).

Per the [W3C DID spec](https://www.w3.org/TR/did-core/#did-resolution), the `resolve` function is expected to return:

```
resolve(did, resolutionOptions) →
   « didResolutionMetadata, didDocument, didDocumentMetadata »
```

[Section 7.1, DID Resolution](https://www.w3.org/TR/did-core/#dfn-didresolutionmetadata) of the DID spec states:

> **didResolutionMetadata**
> A [metadata structure](https://www.w3.org/TR/did-core/#metadata-structure) consisting of values relating to the results of the [DID resolution](https://www.w3.org/TR/did-core/#dfn-did-resolution) process which typically changes between invocations of the resolve and resolveRepresentation functions, as it represents data about the resolution process itself. This structure is REQUIRED, and in the case of an error in the resolution process, this MUST NOT be empty. This metadata is defined by [7.1.2 DID Resolution Metadata](https://www.w3.org/TR/did-core/#did-resolution-metadata). If resolveRepresentation was called, this structure MUST contain a contentType property containing the Media Type of the representation found in the didDocumentStream. If the resolution is not successful, this structure MUST contain an error property describing the error.
>
> **didDocument**
> If the resolution is successful, and if the resolve function was called, this MUST be a [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents) abstract data model (a [map](https://infra.spec.whatwg.org/#maps)) as described in [4. Data Model](https://www.w3.org/TR/did-core/#data-model) that is capable of being transformed into a [conforming DID Document](https://www.w3.org/TR/did-core/#dfn-conforming-did-document) (representation), using the production rules specified by the representation. The value of [id](https://www.w3.org/TR/did-core/#dfn-id) in the resolved [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents) MUST match the [DID](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers) that was resolved. If the resolution is unsuccessful, this value MUST be empty.
>
> **didDocumentStream**
> If the resolution is successful, and if the resolveRepresentation function was called, this MUST be a byte stream of the resolved [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents) in one of the conformant [representations](https://www.w3.org/TR/did-core/#representations). The byte stream might then be parsed by the caller of the resolveRepresentation function into a [data model](https://www.w3.org/TR/did-core/#data-model), which can in turn be validated and processed. If the resolution is unsuccessful, this value MUST be an empty stream.
>
> **didDocumentMetadata**
> If the resolution is successful, this MUST be a [metadata structure](https://www.w3.org/TR/did-core/#metadata-structure). This structure contains metadata about the [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents) contained in the didDocument property. This metadata typically does not change between invocations of the resolve and resolveRepresentation functions unless the [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents) changes, as it represents metadata about the [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents). If the resolution is unsuccessful, this output MUST be an empty [metadata structure](https://www.w3.org/TR/did-core/#metadata-structure). Properties defined by this specification are in [7.1.3 DID Document Metadata](https://www.w3.org/TR/did-core/#did-document-metadata).

Given that it seems that, in the event of an error, the DID Resolution Result of the `resolve` function should look something like this:

```json
{
    "didResolutionMetadata": {
        "error": "invalidDid"
    },
    "didDocument": {},
    "didDocumentMetadata": {}
}
```

Referencing the relevant excerpts from the DID spec:
* `didResolutionMetadata`: "This structure is REQUIRED, and in the case of an error in the resolution process, this MUST NOT be empty."
* `didDocument`: "If the resolution is unsuccessful, this value MUST be empty."
* `didDocumentMetadata`: "If the resolution is unsuccessful, this output MUST be an empty metadata structure."

Given the use of the terminology "empty" and "structure" it would seem that an empty object (`{}`) is the most appropriate value to select.

**Comment by frankhinek** [comment]
@andresuribe87 pointed out on Discord that there was a [recent discussion](https://discord.com/channels/937858703112155166/949067728709369856/1182724638002921482) on this topic.

**Comment by andresuribe87** [comment]
I think the proposal makes sense. Crafting a PR to correct the test-vectors to have `{ }`.

**Comment by mistermoe** [comment]
Contrary to `didDocumentMetadata` where the spec text is clear about **empty metadata structure**,  the spec text has left room for interpretation wrt how to represent `empty` for `didDocument`

I tend to lean towards using `null` over an empty object for `didDocument` because it seems more straightforward  to check for `null` vs. checking to make sure an "object" is empty across languages. Depending on the language,  when parsed, "empty object" can be represented as:
* class instances
* structs
* vectors

**Comment by mistermoe** [comment]
> `didDocument`: "If the resolution is unsuccessful, this value MUST be empty."

looks like the draft spec for did resolution also considers this to be null. [Reference](https://w3c-ccg.github.io/did-resolution/#resolving-algorithm)

<img width="1107" alt="image" src="https://github.com/TBD54566975/sdk-development/assets/4887440/ea117b17-508a-4df7-8572-23d3c105ec13">

**Comment by mistermoe** [comment]
correct
